---
title: Revamp
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: David Klein · Freshly Ground Design
descripiton: David Klein, a designer in San Francisco who loves coffee
author: David Klein
url: http://diklein.com
googleID: 39930910-6
paginate: 5
paginate_path: "/journal/page:num/"
permalink: "/:year/:month/:title.html"
exclude:
- Rakefile
plugins:
- jekyll-paginate
sass:
  style: compressed
manifest_name: David Klein · Freshly Ground Design
manifest_short_name: David Klein
manifest_lang: en
manifest_background_color: white
manifest_display: standalone
